name: Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install uv based on the version defined in pyproject.toml
        uses: astral-sh/setup-uv@v6
        with:
          version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest
